Update release workflows using parallelization
arduino/tooling-project-assets pull request #277
Opened 2022-10-11 14:14 UTC by MatteoPologruto

Updates:
- `release-go-task`, `publish-go-nigthly-task` and `publish-go-tester-task` now use a matrix to run build tasks simultaneously instead of running them sequencially with `dist:all`. This also allows to directly upload a different artifact for each build in `publish-go-tester-task`.
- Checksums are calculated in the release creation job only.
- `DistTasks` no longer has a `dist:all` task.

This changes were originally introduced with PR [1883](https://github.com/arduino/arduino-cli/pull/1883) in the [arduino-cli](https://github.com/arduino/arduino-cli) repository.

2022-10-13 12:53 UTC, per1234 requested changes

2022-10-13 15:27 UTC, MatteoPologruto commented
Thanks for the suggestions @per1234! Here is a workflow run in which I tested the changes made to `publish-go-tester-test`: https://github.com/MatteoPologruto/arduino-cli/actions/runs/3243497130
Let me know if there is something else that need to be modified.

2022-10-13 22:32 UTC, per1234 approved these changes
Excellent work. Thanks Matteo!

2022-10-14 10:50 UTC, merged

2023-03-17 14:51 UTC, umbynos commented on workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-task.yml
> -          echo "::set-output name=checksum-${{ matrix.artifact.name }}::$CHECKSUM_LINE"
@MatteoPologruto In this PR we forgot to remove https://github.com/arduino/tooling-project-assets/pull/277/files#diff-3377c3cd39d3d2deebfce56bb1ffc4097c576a1eb06511dc4907daa926987627L56-L58