add the license headers check in go files
arduino/tooling-project-assets pull request #354
Opened 2023-05-17 14:09 UTC by alessio-perugini

2023-05-17 14:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino/tooling-project-assets?pullRequest=354) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/arduino/tooling-project-assets?pullRequest=354) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino/tooling-project-assets?pullRequest=354) it.</sub>

2023-10-06 14:49 UTC, umbynos requested changes
Overall looks good, I would only like to have a `license_header.tpl` template in this PR. This repo is intended to make copy-paste possible with minimal configuration and not having that file or at least instructions on how to structure it is a problem

2025-08-06 19:49 UTC, closed without merging

2025-08-07 00:51 UTC, per1234 commented
@alessio-perugini please provide an explanation of why you closed this. It seems like a useful feature that should eventually added to the assets.

2026-02-27 10:32 UTC, dido18 commented
superseeded by https://github.com/arduino/tooling-project-assets/pull/718